apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  labels:
    app: mongo-express
    pod-template-hash: 78f4bf45f7
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
  selector:
    app: mongo-express
  type: LoadBalancer
