apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb-deployment
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb-deployment
